version: '3.3'

services:
  healthcare-api:
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_JPA_SHOW_SQL=true
      - LOGGING_LEVEL_COM_EXAMPLE_SESSION_DEMO=DEBUG
      - LOGGING_LEVEL_ORG_HIBERNATE_SQL=DEBUG
    volumes:
      - ./logs:/app/logs
    ports:
      - "8080:8080"
      - "5005:5005"  # Debug port
    command: >
      sh -c "
        java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
        -Dspring.profiles.active=dev
        -jar app.jar
      " 